services:
  database:
    image: mysql:8.4
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kos_db
      MYSQL_USER: kos_user
      MYSQL_PASSWORD: kos_password

    volumes:
      - mysql_data:/var/lib/mysql

    ports:
      - "3306:3306"


  backend:
    build:
      context: ./backend

    restart: unless-stopped

    environment:
      DATABASE_URL: mysql+pymysql://kos_user:kos_password@database:3306/kos_db

    ports:
      - "8000:8000"

    depends_on:
      - database


  frontend:
    build:
      context: ./frontend

    restart: unless-stopped

    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:8000/api/v1
      NEXT_PUBLIC_MEDIA_BASE_URL: http://localhost:8000

    ports:
      - "3000:3000"

    depends_on:
      - backend


volumes:
  mysql_data: